
insert into meme (id, name, description, image_url, created_user, last_modified_user) values (0, '( ͡° ͜ʖ ͡°) / Lenny Face', '( ͡° ͜ʖ ͡°) is an emoticon created with unicode character symbols. The face is often used to spam forums and image boards, similar to the Japanese word “desu”. On 4chan, it has also come to be known as “Le Lenny Face” or “Le Face Face”', '/images/memes/0000LennyFace.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (1, 'Fuck Yea', 'Fuck Yea is a series of four-pane cartoon strips featuring a stick figure looking rather self-complacent and quite frankly, for all the right reasons. Originally posted via /b/ board on February 11, 2010, these cartoons illustrate all sorts of triumphant moments in our daily lives that make us feel awesome, like when you wake up a few seconds before the morning alarm goes off. This phenomenon can be also seen as the antithesis to Rageguy comics, another four-pane series originating from 4chan circa late 2008.', '/images/memes/0001FuckYea.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (2, 'Bitcoin to the moon', 'Bitcoin is a virtual cryptocurrency regulated by a peer-to-peer network that creates a time-stamped register yielding chains of valid transactions. Unlike other digital currency systems or credit payments, Bitcoins are treated like cash and transactions cannot be reversed.', '/images/memes/0002BitCoinToMoon.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (3, 'Forever Alone', 'Forever Alone is an exploitable rage comic character that is used to express loneliness and disappointment with life. The face has also been used as an advice animal and inspired the creation of the snowclone template “Forever an X.”', '/images/memes/0003ForeverAlone.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (4, 'Yao Ming Face / Bitch Please', 'Yao Ming Face (sometimes referred to as “Fuck That Guy” or “Dumb Bitch”) is a rage comic-style contour drawing of the professional basketball player Yao Ming wearing a hearty smile. The image is typically used as a reaction face to convey a dismissive attitude towards someone else’s input in online discussions, then usually following something that one ups their input.', '/images/memes/0004BitchPlease.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (5, 'Troll Face', 'Trollface is a rage comic character wearing a mischievous smile that is meant to represent the facial expression of an Internet troll. The image is most commonly used to portray a character as a troll in rage comics, or alternatively, to identify oneself or another participant as such in online discussions.', '/images/memes/0005TrollFace.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (6, 'Rage Guy FU', 'The name Rageguy refers to the main character of a series of crudely-drawn comics typically consisting of four panes, portraying situations which can bring rage and exasperation, with the main character screaming with anger as a result. Due to its simplicity and exploitability, Rageguy has been proven popular thus being evolved into a comic series now known as Rage Comics.', '/images/memes/0006RageGuyFU.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (7, 'True Story', 'True Story is a rage comic character based on a black and white contour drawing of How I Met Your Mother character Barney Stinson (played by actor Neil Patrick Harris) smiling smugly while holding a wine glass. Often accompanied by the text “true story,” the character can mostly be found in the final panel of a rage comic to either indicate or falsely claim that it is based on a true story.', '/images/memes/0007TrueStory.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (8, 'Nyan Cat / Pop Tart Cat', 'Nyan Cat, also known as Pop Tart Cat, is an 8-bit animation depicting a cat with the body of a cherry pop tart flying through outer space. While absurd themes like flying kittens and pastry cats have been around for some time, the surreal humor behind this particular combination has captivated YouTubers and online art communities, spawning fan illustrations as well as user-interface designs and homebrew games across multiple platforms.', '/images/memes/0008NyanCat.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (9, 'Pepe the Frog', 'Pepe the Frog is an anthropomorphic frog character from the comic series Boy’s Club by Matt Furie. On 4chan, various illustrations of the frog creature have been used as reaction faces, including Feels Good Man, Sad Frog, Angry Pepe, Smug Frog and Well Meme’d.', '/images/memes/0009PepeTheFrog.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (10, 'Obama Rage Face / Not Bad', 'Obama Rage Face (also known as “Not Bad” Face) is a rage comic reaction face based on a press photograph of Barack Obama wearing a sturgeon face during his official state visit to the United Kingdom in May 2011. The image is used as a positive response to a pleasant surprise or an outcome of an event that has surpassed one’s expectation, similar to the usage of “everything went better than expected” face.', '/images/memes/0010ObamaNotBad.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (11, 'Wojak / Feels Guy', 'Feels Guy, also known as Wojak, is an MS Paint illustration of a bald man with a sad expression on his face. It is often used as a reaction image to represent feelings such as melancholy, regret or loneliness.', '/images/memes/0011wojak.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (12, 'Slender Man', 'Slender Man (a.k.a Slenderman) is a mythical creature often depicted as a tall, thin figure wearing a black suit and a blank face. According to the legend, he can stretch or shorten his arms at will and has tentacle-like appendages protruding from his back. Depending on the interpretations of the myth, the creature may cause memory loss, insomnia, paranoia, coughing fits (nicknamed “slendersickness”), photograph/video distortions and can teleport at will. The urban legend has inspired fan arts, fictional creepypastas and a mockumentary series in the style of the 1999 indie horror film Blair Witch Project. As the character has grown in popularity, he’s gained a number of other nicknames including The Operator, Der Großmann, Mr. Slim, The Administrator, Daddy LongLegs, Mr. Thin, The Tall Man, The Thin Man and Slendy.', '/images/memes/0012slenderman.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (13, 'Flipping Tables', 'Flipping Tables (written as: (╯°□°）╯︵ ┻━┻) is a text-based emoticon depicting a person flipping a table out of rage. Primarily used by East Asian internet users to express rage, the emoticon became popular among Western internet users following its introduction through internationally popular online games.', '/images/memes/0013FlippingTables.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (14, 'Hodl', 'Hodl is an intentional misspelling of the word “hold,” which is used among cryptocurrency enthusiasts when encouraging traders to resist the urge to sell one’s holdings in response to market fluctuations. Following the term’s surge in popularity online, the backronym “hold on for dear life” was subsequently attributed to the term.', '/images/memes/0014hodl.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (15, 'Grumpy Cat', 'Grumpy Cat is the nickname given to Tardar Sauce, a snowshoe cat that rose to online fame after several pictures of her annoyed facial expressions were posted to Reddit in late September 2012.', '/images/memes/0015GrumpyCat.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (16, 'Neil deGrasse Tyson', 'Neil deGrasse Tyson Reaction is a rage comic character and reaction face of astrophysicist Neil deGrasse Tyson making a defensive gesture. The character image is sometimes associated with the catchphrase “Watch out guys, we’re dealing with a badass over here” that is used to mock arrogant and boastful statements made by Internet users.', '/images/memes/0016NeildeGrasseTyson.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (17, 'Me Gusta', 'Me Gusta is a rage comic face that is typically used to express one’s approval of an awkward or perverse situation. The caption “Me gusta” translates to “I like it” in Spanish. In its beginning, the phrase conveyed an odd sense of pleasure in sexually perverse contexts, but the meaning has since broadened to describe a more general state of being disturbed and pleased at the same time.', '/images/memes/0017MeGusta.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (18, 'Challenge Accepted', '“Challenge Accepted” is an expression used to indicate that the speaker is willing to attempt completing a difficult task. The phrase is often associated with a rage comic character illustrated as a stick figure with crossed arms and a smug facial expression.', '/images/memes/0018ChallengeAccepted.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (19, 'Okay Guy', '“Okay Guy is a sullen-looking rage comic character who is accompanied by the caption “okay.” The face is often used in the final panel of comics meant to convey a feeling of hopeless resignation.', '/images/memes/0019OkayGuy.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (20, 'Doge', 'Doge is a slang term for “dog” that is primarily associated with pictures of Shiba Inus (nicknamed “Shibe”) and internal monologue captions on Tumblr. These photos may be photoshopped to change the dog’s face or captioned with interior monologues in Comic Sans font.', '/images/memes/0020doge.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (21, '"Y U NO" Guy', '“Y U NO” Guy (also known as “Y U No [X]?”) is an image macro series using SMS shorthands and carefree grammar as a way to bring someone’s attention on a particular subject or issue. The unique facial expression worn by stick-figure character is believed to have been traced from the Japanese sci-fi manga / anime series Gantz.', '/images/memes/0021YUNO.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (22, 'Oh Crap / OMG Rage Face', 'The Oh Crap or OMG Face refers to an exploitable image used in rage comics to express an array of feelings including astonishment, revelation, or sheer rage. It is often paired with red or white text, summing up the character’s thoughts. It is also used to represent a Gropaga, or follower of Inglip.', '/images/memes/0022OMGRageFace.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (23, 'I Know That Feel Bro', '“I Know That Feel Bro” (also known as “to uczucie” or “to uczócie”) is an Internet slang expression used to convey empathy towards or agree with someone else’s feeling or opinion. The expression, which roughly means “I feel you, bro,” is typically accompanied by a contour- drawing reaction image of two bald men embracing each other expressionlessly. The face has been used as an exploitable character and is often seen in “that feel when” (TFW) threads on image boards, which describe an emotional situation or event.', '/images/memes/0023IKnowThatFeelBro.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (24, 'Mother of God', 'Mother of God… is a rage comic character of a man staring intently at something as he takes his sunglasses off. It can be also used outside of rage comics to express astonishment or disbelief in response to a shocking image or a video. Similar to the colloquial usage of the phrase, the reaction face can be used to either indicate approval or disapproval, depending on the context. When used in the context of rage comics, it is usually preceded by a stick-figure drawing of the same man humming and walking with sunglasses still on.', '/images/memes/0024MotherOfGod.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (25, 'Scumbag Steve', 'Scumbag Steve is an image macro series featuring a kid with a sideways fitted cap standing in a hallway. The overlaid text generally centers around unethical behavior regarding drugs, partying, and other hedonistic behaviors.', '/images/memes/0025ScumbagSteve.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (26, 'Overly Attached Girlfriend', 'Overly Attached Girlfriend is an advice animal image macro featuring webcam picture of vlogger Laina Morris and various captions portraying her in the stereotype of an overprotective and clingy girlfriend.', '/images/memes/0026OverlyAttachedGF.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (27, 'Tough Spongebob', 'Tough Spongebob also known as “*I Only Cried For 20 Minutes*,” is an advice animal image macro series based on a still image from an episode of the children’s animated TV series Spongebob Squarepants. The captions typically describe an unfortunate situation brought on by oneself, beginning with “I’ll have you know” and concluding with “and I only cried for 20 minutes.”', '/images/memes/0027ToughGuySpongeBob.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (28, 'Yo Dawg', 'Yo Dawg, or Sup Dawg, is an image macro series based on portrait shots of American hip hop artist Alvin Nathaniel Joiner,[10] better known by his stage name Xzibit, and humorous captions that are composed around the recursive phrasal template “Yo Dawg, I herd you like (noun X), so I put an (noun X) in your (noun Y) so you can (verb Z) while you (verb Z).” Since rising to popularity in early 2007, the series has been considered one of the most well-known and longest lasting examples of recursive humor on the Internet.', '/images/memes/0028YoDawg.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (29, 'Success Kid', 'Success Kid, sometimes known as I Hate Sandcastles, is a reaction image of a baby at a beach with a smug facial expression. It has been used in image macros to designate either success or frustration. In early 2011, the original image was turned into an advice animal style image macro with captions describing a situation that goes better than expected.', '/images/memes/0029SuccessKid.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (30, 'You Don’t Say?', '“You Don’t Say?” is a rage comic face based on a contour drawing of Nicolas Cage that is that is used as a sarcastic response to an obvious observation or statement, in similar vein to “O RLY” image macros.', '/images/memes/0030YouDontSay.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (31, 'Good Guy Greg', 'Good Guy Greg (GGG) is an advice animal image macro series featuring a photo of a square-jawed man smiling at the camera with a marijuana cigarette in his mouth. As the antithesis of Scumbag Steve, the captions generally depict the character as kind, generous or empathetic to other people.', '/images/memes/0031GoodGuyGreg.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (32, 'If You Know What I Mean', '“If You Know What I Mean” is a rage comic character based on a still frame of actor Rowan Atkinson portraying the fictional character Mr. Bean. It is used to point out a double entendre in a post or image macro, commonly in the form of sexual innuendo. Although originally created as a rage face, the character is also used in vertical comics in a similar manner to the You Don’t Say? and We’ve Got a Badass Over Here reaction images.', '/images/memes/0032IfUKnowWhatIMean.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

insert into meme (id, name, description, image_url, created_user, last_modified_user) values (33, 'Dolan', 'Dolan is an MS Paint web comic series featuring a variety of poorly drawn Disney cartoon characters. The main character Dolan, based on Donald Duck, is often portrayed as a psychotic killer and sex addict.', '/images/memes/0033Dolan.jpg','hello@cryptomemes.info','hello@cryptomemes.info');

