App.contracts.Meme.deployed().then(function(instance) {memeInstance = instance});

memeInstance.createContractMeme("( ͡° ͜ʖ ͡°) / Lenny Face");
memeInstance.createContractMeme("Fuck Yea");
memeInstance.createContractMeme("Bitcoin to the moon");
memeInstance.createContractMeme("Forever Alone");
memeInstance.createContractMeme("Yao Ming Face / Bitch Please");
memeInstance.createContractMeme("Troll Face");
memeInstance.createContractMeme("Rage Guy FU");
memeInstance.createContractMeme("True Story");
memeInstance.createContractMeme("Nyan Cat / Pop Tart Cat");
memeInstance.createContractMeme("Pepe the Frog");
memeInstance.createContractMeme("Obama Rage Face / Not Bad");
memeInstance.createContractMeme("Wojak / Feels Guy");
memeInstance.createContractMeme("Slender Man");
memeInstance.createContractMeme("Flipping Tables");
memeInstance.createContractMeme("Hodl");
memeInstance.createContractMeme("Grumpy Cat");
memeInstance.createContractMeme("Neil deGrasse Tyson");
memeInstance.createContractMeme("Me Gusta");
memeInstance.createContractMeme("Challenge Accepted");
memeInstance.createContractMeme("Okay Guy");
memeInstance.createContractMeme("Doge");
memeInstance.createContractMeme("Y U NO Guy");
memeInstance.createContractMeme("Oh Crap / OMG Rage Face");
memeInstance.createContractMeme("I Know That Feel Bro");
memeInstance.createContractMeme("Mother of God");
memeInstance.createContractMeme("Scumbag Steve");
memeInstance.createContractMeme("Overly Attached Girlfriend");
memeInstance.createContractMeme("Tough Spongebob");
memeInstance.createContractMeme("Yo Dawg");
memeInstance.createContractMeme("Success Kid");
memeInstance.createContractMeme("You Don’t Say?");
memeInstance.createContractMeme("Good Guy Greg");
memeInstance.createContractMeme("If You Know What I Mean");
memeInstance.createContractMeme("Dolan");
